### PR TITLE
Better healthcheck

### PR DESCRIPTION
**Pull request by qdm12**
Refers to #133 

I will test it in the coming days to ensure it works as expected and don't get blocked / throttled.

### CODE REVIEW

**Comment by Frepke** [comment]
For the first time my container runs unhealthy 😢 
` End 2020-06-04T07:45:48.05562041+02:00
ExitCode 1
Output Public IP address xx.xx.xxx.105 does not match VPN ip address xx.xx.xxx.104 on file
Start 2020-06-04T07:45:46.714592228+02:00`

**Comment by Frepke** [comment]
No, I pulled the latest version and docker-compose up -d

**Comment by Frepke** [comment]
My public IP address is very often different from the IP address in the container log.
I mentioned a long time ago when I used PIA, now with Surfshark it's the same.

**Comment by qdm12** [comment]
Uh that's odd. Anyway, I just fixed #170  which describes your problem, let's see if this resurfaces. Now it's checking against all the vpn IP addresses in the openvpn configuration file.

Strangely enough, my pia container has been running for 45 hours healthily 🤔 

If it's still unhealthy maybe it's because the IP addresses of the VPN servers act as a sort of gateway, but let's see how it goes.

**Comment by Frepke** [comment]
Running version latest built on 2020-06-04T22:14:44Z (commit f6a2aac)

Still unhealthy:

``` "Start": "2020-06-05T07:25:51.980269096+02:00",
      "End": "2020-06-05T07:25:53.374607856+02:00",
      "ExitCode": 1,
      "Output": "Public IP address xx.xx.xxx.xx5 does not match any of the VPN ip addresses xx.xx.xxx.xx4 1194\n"

**Comment by qdm12** [comment]
In an unhealthy container, can you please check if your VPN IP address shown in `docker exec gluetun ip route` matches:

1. `docker exec gluetun wget -qO- https://ipinfo.io/ip`
1. `docker exec gluetun cat /ip`
1. `docker exec cat /etc/openvpn/target.ovpn | grep remote`

Thanks!

**Comment by Frepke** [comment]
> In an unhealthy container, can you please check if your VPN IP address shown in `docker exec gluetun ip route` matches:

docker exec gluetun ip route
```
0.0.0.0/1 via 10.8.8.1 dev tun0 
default via 172.17.0.1 dev eth0 
10.8.8.0/24 dev tun0 proto kernel scope link src 10.8.8.8 
10.54.1.0/24 via 172.17.0.1 dev eth0 
89.46.223.104 via 172.17.0.1 dev eth0 
128.0.0.0/1 via 10.8.8.1 dev tun0 
172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2 
```
> 
>     1. `docker exec gluetun wget -qO- https://ipinfo.io/ip`
89.46.223.105
> 
>     2. `docker exec gluetun cat /ip`
89.46.223.104
> 
>     3. `docker exec gluetun cat /etc/openvpn/target.ovpn | grep remote`
89.46.223.104 1194
> 
> 
> Thanks!

I've a static target ip in the compose-file.
This morning I tested it with no static target ip, but all my wan-ip wasn't in the list, the closest match was also one of.

**Comment by qdm12** [comment]
Thanks! Let's continue the discussion on #170

**Pull request merged**
