### PR TITLE
Fix containers connected loosing connection when openvpn reconnects

### PR DESCRIPTION
**Pull request by qdm12**
- `persist-remote-ip` openvpn flag added

Might cancel #108 if it proves successful

### CODE REVIEW

**Comment by gurabli** [comment]
> * `persist-remote-ip` openvpn flag added
> 
> Might cancel #108 if it proves successful

I just need to pull the latest tag and this will take effect or an ENV variable is needed (PIA)?

**Comment by Frepke** [comment]
> 
> 
> > * `persist-remote-ip` openvpn flag added
> > 
> > Might cancel #108 if it proves successful
> 
> I just need to pull the latest tag and this will take effect or an ENV variable is needed (PIA)?

For the test, you've to pull with the tag :persist-remote-ip instead of :latest.

**Comment by gurabli** [comment]
> > > * `persist-remote-ip` openvpn flag added
> > > 
> > > Might cancel #108 if it proves successful
> > 
> > 
> > I just need to pull the latest tag and this will take effect or an ENV variable is needed (PIA)?
> 
> For the test, you've to pull with the tag `:persist-remote-ip` instead of `:latest`.

Thanks! I pulled and lets see hwo is it performing. I don't need to see anything in the logs, correct?

**Comment by Frepke** [comment]
> 
> 
> > > > * `persist-remote-ip` openvpn flag added
> > > > 
> > > > Might cancel #108 if it proves successful
> > > 
> > > 
> > > I just need to pull the latest tag and this will take effect or an ENV variable is needed (PIA)?
> > 
> > 
> > For the test, you've to pull with the tag `:persist-remote-ip` instead of `:latest`.
> 
> Thanks! I pulled and lets see hwo is it performing. I don't need to see anything in the logs, correct?

The only thing changed is an extra variable in the .ovpn file. Don't think you see anything in the logs (not sure). Use the container and see how it reacts.

**Comment by qdm12** [comment]
Hello all, sorry I missed those comments somehow!

It just adds `persist-remote-ip` in the ovpn config file, which might solve reconnection. On the other hand, please try #143  (tag `:restart`) (pull request #144) which basically restarts openvpn if it crashes from within the container so that linked containers don't lose their connection.

I tried manually disconnecting the ethernet cable for a few minutes, openvpn tries to restart for a few minutes, then crashes and then gets re-launched successfully. It *should* solve a bunch of problems if it works out for you 😉 

Thanks!

**Comment by qdm12** [comment]
So from what I've gathered, you all don't really have problems of openvpn losing its connection (on `:latest`) but would like to restart/update the pia container without having to restart the other connected containers right?

I think anyway #144 would be better than this modification, that is, if you have openvpn disconnection issues (I don't for example).

**Pull request closed without merging**
